# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- none

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and push image to container registry
      inputs:
        containerRegistry: 'AzureContainerRegistryRiccardo'
        repository: 'demos/BlazorServerWithDocker'
        command: 'buildAndPush'
        Dockerfile: '**/dockerfile'
        tags: |
          $(Build.BuildId)
          latest